[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bba940bd8a26881c395df234e8aec8e14367f301"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "fb4b49a52b0f575770c9b68886b4c5f398494af192eaa22f435d76674b17ad3f"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.aarch64-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7c7448c7e1bfd6525fb83ab0fb925c9f1989f10"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "029ba446e0fd23ac843f7e26009dd55b334a39d1cb3f9fd03e8ec94a32cdd503"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.aarch64-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "10cffb72ac8e3a1ded2623be53916c65a08e8cf2"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "17aefc05198c1c8b82502d5cc7f9c5001ca2424bc25da71799b0d86d034fce28"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.aarch64-linux-musl-cxx03.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9859a73f8387c37a9b57be8a6a0f171c528e49a"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "1bddf44786367a63b8fafe705323bf10cf064c56b98480ab0cf3e6d3cf13b2b5"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.aarch64-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa84a16b14d1f6a663b90835b12899b630fd6f95"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "7d82bc3c5aa4b333a4f282f8d82983b9ce9b687eb07194a7ff92632dbbf79640"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[lib4ti2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47b90ac4083aaafdf2e807a5aaefdca895a51008"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "ba7cac9170c373deb69cd4353b7f0b21fd73e8de92a76ea11e18878e3a6f68a5"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e29aef5bec9bee4c7a0ad4f9a84fb425f48020ed"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "68b6669832e4fa7b632897a338db990c2396ff4092cb706f083a2ef286331ee0"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.armv7l-linux-musleabihf-cxx03.tar.gz"
[[lib4ti2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4045c72f03cf8cad53ea0dfd968a54e857ba442f"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "a41b6fed6608ca53614669464d3bf6987e963fa540fb4bcda5cc10e92dbeb089"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89e1c3729bc0c0372365da31d76b421af87f731f"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "862d09ee4a87fbed4b3e626863c069e099d4a4efb9f96b42e3827063d81fbfa9"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.i686-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ec9d456d4416497bcd503b7d8e4685a22978b93"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "c21da6162dcdcd1a9d8473488dedef6e7600924c7f0470f3d21d81320b91c204"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.i686-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3fb6e64f9a710e7e1ed30a9a3131034684ea6532"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "0f5011acb47ce489441c2524501dacd43d420162f5b9946e7f49b7c2c898624e"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.i686-linux-musl-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3716a00cfbdc8df0c7a02b8c70ad4eb71145f92f"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "4faecb9581c19a68e77c8e9700ca57622bd1b30fbcc61342f4525ce6acb4570f"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.i686-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1793a3243e0be8fe0b6bcdc26c2e355f20840558"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "ceba17b4f8ad1da0e9a93ea928ed312316b033298c3377cd58f715b203999b03"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.i686-w64-mingw32-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a30f3fe67e514b1c5479481916ece0bc56c40a7"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "f342e2a3f6e9f9e23d3081526bd396e408aa649772d5f9cc51025b0fc2a48d6a"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.i686-w64-mingw32-cxx11.tar.gz"
[[lib4ti2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4acdbf9b4940531ba90cdcad54fa7c701a3a4cb"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "81fc408e116c69919d3e0ce997684796d62d1bd9ea66467ef378e021857d11ec"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.powerpc64le-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0cefc11ab366807f0cab6fa4bd0abda1a585892"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "a1f2ea6d2b74029330075772d2ee9fa9c6d781a143687e095a87580dfdea6ab0"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.powerpc64le-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
git-tree-sha1 = "4a603abc31013e04bcdcb12365beb6326a22acf9"
os = "macos"

    [[lib4ti2.download]]
    sha256 = "0d409cf81131f00498f5f737dcc64928c9aece0d1296a81afb82b0a240c71a62"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.x86_64-apple-darwin.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b7befe72290cfabebb1d9db6b79ab2d087ae2c0"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "b4405a505f2ab5db22d0040cac2d14a13a0b2cac9d6dd20cd6c00d5095e86f18"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.x86_64-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15a825d54b4da29c43c32eb5078167cb4c95a651"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "ea0053e93c0be4d02628a8620e93a09c2b6a4260748df875fee55a9cb151401d"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.x86_64-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c885e2c112a6807a9e190f9a7b3ba92fdbb15d00"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "7594882deb9962d3544c06da37fae979e977ea826ba87d89b36143498c0c72d8"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.x86_64-linux-musl-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81123d1dce5d7a786af90d42b3c479ef5c911cf6"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "d7c57352954ed05c65299f6f2bd5ade76a0bbe93342a9422e03f0c787f1b7b6a"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.x86_64-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
git-tree-sha1 = "ab76e73e8b8ce2742e497a6d5896d678a4711eb4"
os = "freebsd"

    [[lib4ti2.download]]
    sha256 = "0c4170d480687be876214d3a3ff2b7f405b48d88c4811f36b11dad8f84e0c116"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.x86_64-unknown-freebsd.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bd23bad268df9c6b8db290cda46b891c05b0683"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "47f9e8310aba66e69cc36e9b0b01c49d5fdd865772e4da1219df5c940a8ad2f2"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f857474883af326450c9af578d09efbd91481ab"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "d1d67d42dfb2690004246347a205c66d8fb34768d50024bcc70f496edf44da0c"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+2/lib4ti2.v1.6.9.x86_64-w64-mingw32-cxx11.tar.gz"
