[[lib4ti2]]
arch = "aarch64"
git-tree-sha1 = "d09045cc558b23da5888886291621e3431d4e72e"
os = "macos"

    [[lib4ti2.download]]
    sha256 = "ca9495e50e069a518bb3ca2a92ed877a30d7cd0f64f2d7eac0902e1c237a071e"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.aarch64-apple-darwin.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5a43a7d9e764ec923f68233f905a3765fe1fa64"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "1aef8c64c97d3866f1df1a9db52c6f2628c7d59d71ff9eb7ce99761e4eb6f56e"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.aarch64-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f22743fead7df9a640bdd1371444e8b937c9d493"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "b1a18cb8924b97d100dae848e8948eea3b4d9d8f2b09700ee472edc9393ee1ea"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.aarch64-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70a4acf3d14a33870574ed7cb3c9638ceb2be408"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "f27591b1e4814e60d0e1ecced81fc00276c453f8aa1eae97ecf340dbaaaee836"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.aarch64-linux-musl-cxx03.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7623db20e40588c7775e42852136e778ee67cb9"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "4a64d5ff5624bce357ec42e5c02e6326cd40d1eb3c6bb4a6e817fa4eb17640c8"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.aarch64-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6a9f7b77ca7a9b89b44eeb43b60a4f40d23341af"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "b18c702b069ebeb6b3d835dd46830f2d3f4fa336f5adc7241539a86eb8959573"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[lib4ti2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75f769d513bdbbf1dc9af60267cb16949209a76d"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "bb1c741740a2764bf8b1ff0fc74aaf84d5b8bf3970cf63ff54fff83214f8d917"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1231937b5e4b70a42db9a52e4d1d554108003b40"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "21aaf3312bcd281acf8455aa140b0b635625df9658fbdd0be323a0b161b55a9c"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.armv6l-linux-musleabihf-cxx03.tar.gz"
[[lib4ti2]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3177c9de98deaf595bb7eebb4f5e646f25891132"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "7748d409658be77d1434916e56b146176775d3fbb61953d9e9960304faa1805e"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.armv6l-linux-musleabihf-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5af2f519d1cacd1f393c07ea116d8034c5c3ef1"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "3d0d8e5ec0aa9364793cd2d80060dc2db30804227559b9f3defb0ff76364c667"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[lib4ti2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bae54855ecb75f72ee036b001ec726a3a81c73e8"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "2c514573310a502c97763529bb8b7733c3e7f3c021bbe0e2343698832f171e8e"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "089b2090c60211428aaa14f905185fe9edef9ab8"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "bc44c9f626a9d701342182e4fdb5d98d7d13cd14ab0aea918d2283938f9606a7"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.armv7l-linux-musleabihf-cxx03.tar.gz"
[[lib4ti2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63daef07c79ecb95c85d87e4950e6acdaab5ed9a"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "92fca99d35e88400bd88cb25c7c2934fa8ef29b0c39dbbcd4e0127eed4bc307a"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.armv7l-linux-musleabihf-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1824754b840fc6cdc2443e9430d58223b1ce6ddd"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "2a0650b293b4627103c9bf0427fa0cca77be2b87ea493e77ab3df63c2036c653"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.i686-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "441265916c45354b32d09194a509d27b76a2348f"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "afdaae2cdfc715599fee6a917fb256387d1e9d5c7694de2aa2e4a92aaee7c2cf"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.i686-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7d8f071eb019aabcd1d23ce99dc839cb3cd83e9"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "56d2f3003089600b10e4b8ea2dfb1c3f449ba43bd6ad3205f69da9fee1290f4d"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.i686-linux-musl-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9da8323671be787fdf337f9ff7d2dedade7b1fcc"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "73928a87e365a0fc91b393ecf22adbd32786375f1224bd5915e017db9a591142"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.i686-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e80b2decaac9288a64c35859b8c42fba8b6b0f7"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "e7fd2198c51e3f95db130c018933a6ad03a6ed5357208abefb8125c270b983b3"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.i686-w64-mingw32-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "603f399b445e7a074192ee0245ddb51ab3fedd86"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "154b2258eae56ba53d63bd89155296eb1afec72c322d1a48498bb983b59e50bd"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.i686-w64-mingw32-cxx11.tar.gz"
[[lib4ti2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f052cbb0a75722bdcd2dcdf8dd8109bb45f49c8"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "6339ec9e6ecccc5297bd2f80367adb9bad8d7be033e6bb62011bf941baabd594"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.powerpc64le-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d21b6453fe6fb10dab3b8c349d62a65ae97988d"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "917e8f80204809244b2e1e96f33a5945eae7bb26ecc4dc992c76f9fc2cc9a121"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.powerpc64le-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
git-tree-sha1 = "be5db2e6a66fe2df8c8928626782c6817cd5cf43"
os = "macos"

    [[lib4ti2.download]]
    sha256 = "f2776703aa337c11cf416184ce2f51e8f511571fbc2bb41a5d763d71de5f4b63"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.x86_64-apple-darwin.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "22d6db5d1a76d07ae28dfed8e53d9538ac6ad7a9"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "58f6e000ebadeecbabeab81330f991c39a059063e1f7f88920366aa89b3a02db"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.x86_64-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4c2f74756952346ab0ed75d00bce010df97fef6"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "a34b70501ff5f9492fb386d91458b1571e0a0d45290520b77fc9f3e0c0ef38f7"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.x86_64-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c8114ce11ea5dfc0b0257a6737e27867f57940f"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "77df7dffe534d4e1a06b2026a9cad0a13bf31098aa9fd0c493d6ffa77144b7c9"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.x86_64-linux-musl-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af5930ad87296877583ccb7f97521517067eac53"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "f6d8a9732f2279090d723d96209b5c8bb549a1280f2b6f49669fdcba86cdf17f"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.x86_64-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
git-tree-sha1 = "27b8d1b7ba873f2f8fc75b296feddb0ad983c249"
os = "freebsd"

    [[lib4ti2.download]]
    sha256 = "1cc6fc24171e1ac377bb6ecae4d319002659b1b4254d69ad6a100c0094505ec7"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.x86_64-unknown-freebsd.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c31d793143d050bd09276a1d049d7674ff12b5b3"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "543f908ee9962a7b2841b3e5f2d0583f8e4a57faef00672b47f30a52ff8ba228"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.x86_64-w64-mingw32-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56850e42269361fe264469b7dd15843f990f4620"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "c02bbf7684e4394db514a5be179831ae4e7b404e853f3a91e7dd4afd3153e6b6"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.10+0/lib4ti2.v1.6.10.x86_64-w64-mingw32-cxx11.tar.gz"
