[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c02d8af28f2bd28ddab7faed51396327bc0afab"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "4e740ad1792649c05323c2adada419df417a5564da3a8a3b06b39ddc7c8e228d"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.aarch64-linux-musl-cxx03.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd0a8cb6aada11b0d6c7d956d7782c4b20a7abee"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "7e04dfc41fb6dbcd8359d70eb889dc125859c8c03c4d43a7ababea7a75e77bb2"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.aarch64-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01be3a404aa8bce9a824b5e5b9569d18dada9202"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "aac3ccca4318407209abf30f5c406ff54a97e0d96837c3fd5bd209b79ec85497"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.armv7l-linux-musleabihf-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79783de3dfc5370c551b0171c07257db4d1c2e12"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "8ceea4d25e8ccac98bc71d93bfb28760720b42ca30e7d9eb0dfb5e4ae11539ca"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-w64-mingw32-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "340be0bc067cd5378a02a9aa9f5a51a97a0dbf4b"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "faacc2bda86b2bd54745c60eff208d6a965543fbdec9727108c27e9a76ee0b9a"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.i686-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95bdba34ed1d2de29ef18e09a4accce41e78de8a"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "986a1b8d770bcccf9069e1d2b8c06d0215369bb42b6a9ed6184c6e7a3bc01061"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-linux-musl-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49deca148ec3dc89e08fea9772454efc56b278ba"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "5d1e821c1d88cd1c44cb45de0a3971ff4949308174ef6ca2b17f3e8465bfc0f2"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cdeca881837bbd2d0235e5a605e7685d3e0bcaf"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "6a27d410d9368fa9bf85b19d8d599551d0cf396cb080a490582edb0f76fc45ca"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.i686-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e22504d9cf09ea124dcbb8d03dfbe24c1fb2c75"
os = "macos"

    [[lib4ti2.download]]
    sha256 = "461d0e4028e128bbfe2fa18264401866e98fda98e34b0417d806ccaecca134b8"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-apple-darwin14-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2ec5892ca464cb2a0321850f3717071cbe950f0"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "1c76c946558e13fee798953289844004a2a844461cc95bcc28c466a6c3637295"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.i686-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b327900e9ed46f645369fe1063943fc3d19a6c7a"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "b46ef1eb3f42607f7c1b9dd4d5911620316958d641f168b72829d73c1d80fc26"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12659962696a028b1c8657f6de30ff2f9e2b2c16"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "6676fec1b34d7932ac7f5e0b5a294290b3d47794ac5a2f23a41adabed98e2de5"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ac53366a482eb9ba57dd0d8ddcfd652a9bf1c5c"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "1f5395d93fb0c2852e1cc40c5a544810bc8af13b1440c31bafd29ba44b67900a"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.powerpc64le-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08624933363b2c5597725c4c4858017249f6b103"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "a0db2f06d629ccd6022d4ca3ef4d96f6f9d9aa4a2743917610787ad1c16b8060"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.aarch64-linux-gnu-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe1f87190e94ea3c023176fc19901c4f4a2f618b"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "a394bbec6e5df129951fbed82ce59703bb7ebdf9f33e2116a154b6983f712015"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-linux-musl-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e2a579a52fe8212b7b5b396796ce289eb532a908"
os = "macos"

    [[lib4ti2.download]]
    sha256 = "6f3e069dc4ae533e57bbf9b0e7b2d749548c9be3e395f13e86ff425e6e893e7e"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-apple-darwin14-cxx03.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a59c95e74905ca629102a37bbb3ab77b18548570"
os = "freebsd"

    [[lib4ti2.download]]
    sha256 = "ef4829bba258e7be1731d5af6e5869a18634af457e8a833a7ea68b6ba49d76f8"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[lib4ti2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5abf497279b34c038a79a1d246f0b32c99bca450"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "01fc963e8a4d73e1144e66543aad8cd4a327692bed25e3121c13e9bd7f715df8"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.powerpc64le-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "680f5addc9e98701eb56e1b18686194cc5406d1c"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "9de8878a8951bbf52c1c52fb1212428111861e055f2a013f411a095b58603dc2"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.i686-w64-mingw32-cxx03.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a59c7fb33f0a118ced693762850cd114d85d437c"
os = "windows"

    [[lib4ti2.download]]
    sha256 = "8cd95ce147d93773c11f9db0ef3f36e56200aadd40ec6bc4b0c9147fb0b60041"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.i686-w64-mingw32-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00ce701464a4113589b8cb615df2404e8e7370dd"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "0ca2fed2d36747447740470ada287786f28f130a5f35dec1009723861f6fc172"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[lib4ti2]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0862c5d4ee77d8825c84ecda61a0894de1bf5574"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "cfc9a310ef188986a7a0e196ec3b1dcb47c57e848342a759837cb15454603fce"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[lib4ti2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c060398e35a29046cbeb76aa1026ccf1cb237034"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "ec697f7e4f38f0ea08001630105080f87e5a5663c649f58a31e8e02a397df959"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.aarch64-linux-gnu-cxx03.tar.gz"
[[lib4ti2]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01be4bb196ab67064d9580d123e84d27ac896f28"
libc = "glibc"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "36a1fc1f60fddd82c3f523353d4b83a5c5744fe495bb6a8cf86149f1b9c23f48"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[lib4ti2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c3ada4bfc84cc7e9c60e9cb022dfec8ee198ea3"
os = "freebsd"

    [[lib4ti2.download]]
    sha256 = "8a97a6a3aedbd42ab63922604cb0e6268cdd8a47699b33569671935ffea7459a"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[lib4ti2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65724cbafbc08cfaa946d08830063d44097b3809"
libc = "musl"
os = "linux"

    [[lib4ti2.download]]
    sha256 = "760eaa777cd50d8a609b434aa55a65ec7e2a553c0f5a453ea494d616e3855949"
    url = "https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/releases/download/lib4ti2-v1.6.9+1/lib4ti2.v1.6.9.i686-linux-musl-cxx03.tar.gz"
